#!/bin/sh

while [ ! -d stm32 ]; do
	cd ..

	if [ "$(pwd)" = "/" ]; then
		echo stm32 directory not found
		exit 1
	fi
done

if [ "$1" = "clean" ]; then
	rm -rf stm32/build
elif [ ! -z "$1" ]; then
	echo "Unknown parameter"
	echo "Usage: $0 [clean]"
else

	if [ ! -d stm32/build ]; then
		mkdir stm32/build
	fi

	cd stm32/build || exit 1

	cmake .. || exit 1
	make -j4 || exit 1 
	stm_flash ./*.bin || exit 1
fi
